vim.keymap.set("n", "<leader>u", vim.cmd.UndotreeToggle)
-- vim.keymap.set("n", "<C-w>h", vim.cmd.TmuxNavigateLeft)
-- vim.keymap.set("n", "<C-w>l", vim.cmd.TmuxNavigateRight)
-- vim.keymap.set("n", "<C-w>j", vim.cmd.TmuxNavigateDown)
-- vim.keymap.set("n", "<C-w>k", vim.cmd.TmuxNavigateUp)
